---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-json
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.0
    hooks:
      - id: reorder-python-imports
        args:
          - --py38-plus
          - --separate-relative

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.6.1
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
        exclude: \.py0\.

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black ./
        language: system
        types: [python]

      - id: prospector
        name: prospector
        entry: prospector --absolute-paths --no-external-config --profile-path .profile.yaml -w profile-validator -D -w mypy -W pep257
        language: system
        types: [python]
